import { Config } from './';
import { toNano } from "locklift";

const GAS_COEFF = 60;

export const config: Config = {
    RELAYS_COUNT: 3,
    RELAY_ROUND_TIME: 60 * 60 * 24 * 30 * 3, // 3 month
    // Time before the election after round starts
    TIME_BEFORE_SET_RELAYS: 60 * 60 * 24 * 7, // 7 days
    // Min delta between next round start and current election end
    MIN_ROUND_GAP_TIME: 60, // 1 minute

    ETH_STAKING_PROXY: '0x9753Cd3Db2150199F61Fd41a45ECCee73F87c0E6',
    ETH_STAKING_START_TIMESTAMP: 1738097723,
    ETH_MULTI_VAULT_PROXY: '0x9753Cd3Db2150199F61Fd41a45ECCee73F87c0E6',

    ETH_CHAIN_IDS: [56, 1, 43114],
    ETH_STAKING_RELAY_VERIFIER: '0x49b9258bdf61BB1D5eFCCC72315095a58C986009',
    ETH_LAST_BLOCK: { 1: 21725546, 56: 46172159, 43114: 56491745 },
    ETH_CONFIRMS_COUNT: { 1: 12, 56: 30, 43114: 30 },

    GAS: {
        ROUND_DEPLOYER_INSTALL_PLATFORM_ONCE: toNano(11 * GAS_COEFF),
        ROUND_DEPLOYER_INSTALL_OR_UPDATE_RELAY_ROUND_CODE: toNano(11 * GAS_COEFF),
        ROUND_DEPLOYER_SET_RELAY_CONFIG: toNano(11 * GAS_COEFF),
        ROUND_DEPLOYER_SET_BRIDGE_EVENT_TON_ETH_CONFIG: toNano(11 * GAS_COEFF),
        ROUND_DEPLOYER_EVENT_INITIAL_BALANCE: toNano(1 * GAS_COEFF),
        ROUND_DEPLOYER_SET_ACTIVE: toNano(11 * GAS_COEFF),

        DEPLOY_ADMIN: toNano(100 * GAS_COEFF),
        DEPLOY_BRIDGE: toNano(1.5 * GAS_COEFF),
        DEPLOY_CONFIGURATION_FACTORY: toNano(1.5 * GAS_COEFF),
        DEPLOY_CONFIGURATION: toNano(2 * GAS_COEFF),
        DEPLOY_CONNECTOR: toNano(2 * GAS_COEFF),
        DEPLOY_ALIEN_TOKEN: toNano(2 * GAS_COEFF),
        DEPLOY_MERGE_ROUTER: toNano(2 * GAS_COEFF),
        DEPLOY_MERGE_POOL: toNano(2 * GAS_COEFF),
        DEPLOY_PROXY_MULTI_VAULT: toNano(1.5 * GAS_COEFF),
        DEPLOY_ROUND_DEPLOYER: toNano(3 * GAS_COEFF),
        DEPLOY_CELL_ENCODER_STANDALONE: toNano(1.5 * GAS_COEFF),

        MERGE_POOL_ADD_TOKEN: toNano(0.5 * GAS_COEFF),
        MERGE_POOL_ENABLE_ALL: toNano(1 * GAS_COEFF),
        MERGE_ROUTER_SET_POOL: toNano(0.5 * GAS_COEFF),

        CONFIGURATION_SET_INITIAL_BALANCE: toNano(0.2 * GAS_COEFF),
        CONFIGURATION_EVENT_INITIAL_BALANCE: toNano(1 * GAS_COEFF),
        CONFIGURATION_SET_END: toNano(0.1 * GAS_COEFF),

        PROXY_MULTI_VAULT_SET_MERGE_POOL_PLATFORM: toNano(0.5 * GAS_COEFF),
        PROXY_MULTI_VAULT_SET_MERGE_POOL: toNano(0.5 * GAS_COEFF),
        PROXY_MULTI_VAULT_SET_MERGE_ROUTER: toNano(0.5 * GAS_COEFF),
        PROXY_MULTI_VAULT_SET_EVM_CONFIGURATION: toNano(0.5 * GAS_COEFF),

        CONNECTOR_ENABLE: toNano(0.5 * GAS_COEFF),

        BRIDGE_CONNECTOR_DEPLOY_VALUE: toNano(1 * GAS_COEFF),
    }
};
