import { Config } from './';
import { toNano } from "locklift";

const GAS_COEFF = 60;

export const config: Config = {
    RELAYS_COUNT: 3,
    RELAY_ROUND_TIME: 60 * 60 * 24 * 30, // 1 month
    // Time before the election after round starts
    TIME_BEFORE_SET_RELAYS: 60 * 60 * 24 * 4, // 4 days
    // Min delta between next round start and current election end
    MIN_ROUND_GAP_TIME: 60, // 1 minute

    ETH_STAKING_PROXY: '0x457ce30424229411097262c2A3A7f6Bc58BDf284',
    ETH_STAKING_START_TIMESTAMP: 1737561772,
    ETH_MULTI_VAULT_PROXY: '0x0D6aED87931dcC3244B2C62b620911D79dE391eF',

    ETH_CHAIN_IDS: [56, 1, 43114],
    ETH_STAKING_RELAY_VERIFIER: '0xff2BBA54912d1C4Fbaa69dA4f788F68e4E9f2A3A',
    ETH_LAST_BLOCK: { 1: 21681098, 56: 45993489, 43114: 42800893 },
    ETH_CONFIRMS_COUNT: { 1: 15, 56: 30, 43114: 200 },

    GAS: {
        ROUND_DEPLOYER_INSTALL_PLATFORM_ONCE: toNano(11 * GAS_COEFF),
        ROUND_DEPLOYER_INSTALL_OR_UPDATE_RELAY_ROUND_CODE: toNano(11 * GAS_COEFF),
        ROUND_DEPLOYER_SET_RELAY_CONFIG: toNano(11 * GAS_COEFF),
        ROUND_DEPLOYER_SET_BRIDGE_EVENT_TON_ETH_CONFIG: toNano(11 * GAS_COEFF),
        ROUND_DEPLOYER_EVENT_INITIAL_BALANCE: toNano(1 * GAS_COEFF),
        ROUND_DEPLOYER_SET_ACTIVE: toNano(11 * GAS_COEFF),

        DEPLOY_ADMIN: toNano(100 * GAS_COEFF),
        DEPLOY_BRIDGE: toNano(1.5 * GAS_COEFF),
        DEPLOY_CONFIGURATION_FACTORY: toNano(1.5 * GAS_COEFF),
        DEPLOY_CONFIGURATION: toNano(2 * GAS_COEFF),
        DEPLOY_CONNECTOR: toNano(2 * GAS_COEFF),
        DEPLOY_ALIEN_TOKEN: toNano(2 * GAS_COEFF),
        DEPLOY_MERGE_ROUTER: toNano(2 * GAS_COEFF),
        DEPLOY_MERGE_POOL: toNano(2 * GAS_COEFF),
        DEPLOY_PROXY_MULTI_VAULT: toNano(1.5 * GAS_COEFF),
        DEPLOY_ROUND_DEPLOYER: toNano(3 * GAS_COEFF),
        DEPLOY_CELL_ENCODER_STANDALONE: toNano(1.5 * GAS_COEFF),

        MERGE_POOL_ADD_TOKEN: toNano(0.5 * GAS_COEFF),
        MERGE_POOL_ENABLE_ALL: toNano(1 * GAS_COEFF),
        MERGE_ROUTER_SET_POOL: toNano(0.5 * GAS_COEFF),

        CONFIGURATION_SET_INITIAL_BALANCE: toNano(0.2 * GAS_COEFF),
        CONFIGURATION_EVENT_INITIAL_BALANCE: toNano(1 * GAS_COEFF),
        CONFIGURATION_SET_END: toNano(0.1 * GAS_COEFF),

        PROXY_MULTI_VAULT_SET_MERGE_POOL_PLATFORM: toNano(0.5 * GAS_COEFF),
        PROXY_MULTI_VAULT_SET_MERGE_POOL: toNano(0.5 * GAS_COEFF),
        PROXY_MULTI_VAULT_SET_MERGE_ROUTER: toNano(0.5 * GAS_COEFF),
        PROXY_MULTI_VAULT_SET_EVM_CONFIGURATION: toNano(0.5 * GAS_COEFF),
        PROXY_MULTI_VAULT_SET_EVM_TOKEN_ROOT: toNano(0.5 * GAS_COEFF),
        PROXY_MULTI_VAULT_SET_EVM_TOKEN_WALLET: toNano(0.5 * GAS_COEFF),
        PROXY_MULTI_VAULT_SET_ONCE_EVM_TOKEN_PLATFORM: toNano(0.5 * GAS_COEFF),

        CONNECTOR_ENABLE: toNano(0.5 * GAS_COEFF),

        BRIDGE_CONNECTOR_DEPLOY_VALUE: toNano(1 * GAS_COEFF),
    }
};
